services:
  nestjs_app_backend_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - mysql_db
    ports:
      - ${PORT}:${PORT}
    environment:
      DB_HOST: 'mysql_db'
      DB_USER: 'myuser'
      DB_PASSWORD: 'password'
      DB_DATABASE: 'test'
      DB_PORT: 3306
    networks:
      - app

  mysql_db:
    image: "mysql/mysql-server:8.0"
    ports:
      - '3306:3306'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: test
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app

volumes:
  db_data:
    driver: local

networks:
  app:
    driver: bridge
