services:
  nestjs_app_backend:
    env_file:
      - ./.env
    container_name: nestjs_app_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres_db
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./src:/app/src
    networks:
      - app
  postgres_db:
    env_file:
      - ./.env
    image: postgres:14.15-alpine3.21
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app

volumes:
  db-data:

networks:
    app:
       driver: bridge

