FROM node:alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npx yarn install

COPY . .

RUN npx yarn build

FROM node:alpine

WORKDIR /app

COPY --from=builder ./app/package.json ./
COPY --from=builder ./app/node_modules ./node_modules
COPY --from=builder ./app/dist ./dist
COPY --from=builder ./app/.env ./

EXPOSE 4000

CMD [ "node" , "./dist/main.js" ]